### ISSUE TITLE
PVS-Studio.cmake license

### ISSUE THREAD

**Issue by silvioprog** [viva64/pvs-studio-cmake-examples#1]
Hello.

Which is the `PVS-Studio.cmake` licensing? Could I distribute it with a LGPLv3 project?!

Thank you!

**Comment by SvyatoslavRazmyslov** [comment]
Apache License 2.0.

**Comment by SvyatoslavRazmyslov** [comment]
@silvioprog 

You can use [PVS-Studio Free](https://github.com/viva64/how-to-use-pvs-studio-free) and ```PVS-Studio.cmake``` in your project.

**Comment by silvioprog** [comment]
Thanks a lot dude! :+1:
