### ISSUE TITLE
Ограничение анализа.

### ISSUE THREAD

**Issue by Hitoku** [viva64/pvs-studio-cmake-examples#14]
Приветствую, столкнулся с такой проблемой как ограничить анализ только моим кодом? Просто у меня в проекте анализ идет еще и в c:\mingw\include использую такие настройки.

CMakeList.txt 
==============================
cmake_minimum_required(VERSION 3.15)
project(untitled1)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -static")

set(SOURCE_FILES main.cpp)
add_executable(untitled1 ${SOURCE_FILES})

include(PVS-Studio.cmake)

pvs_studio_add_target(TARGET analyze ALL
        OUTPUT FORMAT errorfile
        ANALYZE ${PROJECT_NAME}
        MODE GA:1,2 OP
        LOG target.err)

==============================
Вывод

 Build | analyze | Debug
"C:\Program Files\JetBrains\CLion 2019.3.4\bin\cmake\win\bin\cmake.exe" --build C:\Users\admin3\CLionProjects\untitled1\cmake-build-debug --target analyze -- -j 2
Scanning dependencies of target untitled1
[ 20%] Building CXX object CMakeFiles/untitled1.dir/main.cpp.obj
[ 40%] Linking CXX executable untitled1.exe
[ 40%] Built target untitled1
Scanning dependencies of target analyze
[ 60%] Analyzing CXX file main.cpp
[ 80%] Generating target.err
Analyzer log conversion tool.
Copyright (c) 2008-2020 OOO "Program Verification Systems"

PVS-Studio is a static code analyzer and SAST (static application security
testing) tool that is available for C and C++ desktop and embedded development,
C# and Java under Windows, Linux and macOS.

Total messages: 573
Filtered messages: 45
www.viva64.com/en/w:1:1: error: Help: The documentation for all analyzer warnings is available here: https://www.viva64.com/en/w/.
c:\mingw\lib\gcc\mingw32\9.2.0\include\stddef.h:350:1: warning: V677 Custom declaration of a standard 'wint_t' type. The declaration from system header files should be used instead.
c:\mingw\include\wctype.h:89:1: warning: V677 Custom declaration of a standard 'wctype_t' type. The declaration from system header files should be used instead.
c:\mingw\include\wctype.h:191:1: warning: V677 Custom declaration of a standard 'wctrans_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:67:1: warning: V677 Custom declaration of a standard '_off_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:75:1: warning: V677 Custom declaration of a standard 'off_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:139:1: warning: V677 Custom declaration of a standard '__time32_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:140:1: warning: V677 Custom declaration of a standard '__time64_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:149:1: warning: V677 Custom declaration of a standard 'time_t' type. The declaration from system header files should be used instead.
c:\mingw\lib\gcc\mingw32\9.2.0\include\stddef.h:143:1: warning: V677 Custom declaration of a standard 'ptrdiff_t' type. The declaration from system header files should be used instead.
c:\mingw\lib\gcc\mingw32\9.2.0\include\stddef.h:209:1: warning: V677 Custom declaration of a standard 'size_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:184:1: warning: V677 Custom declaration of a standard '_dev_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:195:1: warning: V677 Custom declaration of a standard '_ino_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:207:1: warning: V677 Custom declaration of a standard 'dev_t' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\types.h:208:1: warning: V677 Custom declaration of a standard 'ino_t' type. The declaration from system header files should be used instead.
c:\mingw\include\stdio.h:220:1: warning: V677 Custom declaration of a standard 'FILE' type. The declaration from system header files should be used instead.
c:\mingw\include\sys\stat.h:173:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\sys\stat.h:180:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\sys\stat.h:188:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\stdint.h:108:1: warning: V677 Custom declaration of a standard 'intptr_t' type. The declaration from system header files should be used instead.
c:\mingw\include\io.h:105:1: warning: V677 Custom declaration of a standard '_fsize_t' type. The declaration from system header files should be used instead.
c:\mingw\include\io.h:342:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\io.h:343:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\time.h:508:1: warning: V795 Please note that the size of the 'time_t' type is not 64 bits. After year 2038, the program will work incorrectly.
c:\mingw\include\wchar.h:530:1: warning: V677 Custom declaration of a standard 'mbstate_t' type. The declaration from system header files should be used instead.
c:\mingw\include\stdint.h:120:1: warning: V677 Custom declaration of a standard 'uintptr_t' type. The declaration from system header files should be used instead.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.h:527:1: error: V769 The '__s' pointer in the '__s + npos' expression equals nullptr. The resulting value is senseless and it should not be used.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.h:734:1: warning: V794 The assignment operator should be protected from the case of 'this == &__str'.
c:\mingw\include\stdlib.h:598:1: warning: V677 Custom declaration of a standard 'div_t' type. The declaration from system header files should be used instead.
c:\mingw\include\stdlib.h:599:1: warning: V677 Custom declaration of a standard 'ldiv_t' type. The declaration from system header files should be used instead.
c:\mingw\include\stdlib.h:631:1: warning: V677 Custom declaration of a standard '_onexit_t' type. The declaration from system header files should be used instead.
c:\mingw\include\stdio.h:821:1: warning: V677 Custom declaration of a standard 'fpos_t' type. The declaration from system header files should be used instead.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.tcc:1309:1: error: V797 The 'find' function is used as if it returned a bool type. The return value of the function should probably be compared with std::string::npos.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.tcc:1325:1: error: V797 The 'find' function is used as if it returned a bool type. The return value of the function should probably be compared with std::string::npos.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.tcc:1355:1: error: V797 The 'find' function is used as if it returned a bool type. The return value of the function should probably be compared with std::string::npos.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.tcc:1558:1: note: V807 Decreased performance. Consider creating a pointer to avoid using the '__in.rdbuf()' expression repeatedly.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\locale_classes.h:522:1: warning: V690 The copy assignment operator is declared as private in the 'locale::_Impl' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\stl_bvector.h:72:1: warning: V690 The '_Bit_reference' class implements the copy assignment operator, but lacks a copy constructor. It is dangerous to use such a class.
C:\Users\admin3\CLionProjects\untitled1\main.cpp:11:1: error: V501 There are identical sub-expressions to the left and to the right of the '==' operator: x == x
C:\Users\admin3\CLionProjects\untitled1\main.cpp:9:1: error: V808 'a' object of 'vector' type was created but was not utilized.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.h:448:1: warning: V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: _M_string_length.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\basic_string.h:579:1: warning: V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: _M_string_length.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\bits\locale_classes.h:514:1: warning: V730 Not all members of a class are initialized inside the constructor. Consider inspecting: _M_index.
c:\mingw\include\_mingw.h:33:1: error: V1040 Possible typo in the spelling of a pre-defined macro name. The '__MINGW_H' macro is similar to '__MINGW__'.
c:\mingw\include\msvcrtver.h:77:1: error: V1040 Possible typo in the spelling of a pre-defined macro name. The '__MINGW_H' macro is similar to '__MINGW__'.
c:\mingw\lib\gcc\mingw32\9.2.0\include\c++\iostream:7:1: error: V1042 This file is marked with copyleft license, which requires you to open the derived source code.
[100%] Built target analyze

Build finished

**Comment by SvyatoslavRazmyslov** [comment]
@Hitoku,

> CONFIG path                   path to PVS-Studio.cfg

Добавьте к проекту файл PVS-Studio.cfg с содержимым:

`exclude-path = c:\mingw`

и пропишите параметр `CONFIG` в `pvs_studio_add_target`.

Должно помочь.

**Comment by Hitoku** [comment]
> @Hitoku,
> 
> > CONFIG path                   path to PVS-Studio.cfg
> 
> Добавьте к проекту файл PVS-Studio.cfg с содержимым:
> 
> `exclude-path = c:\mingw`
> 
> и пропишите параметр `CONFIG` в `pvs_studio_add_target`.
> 
> Должно помочь.

Работает, благодарю.
