### ISSUE TITLE
[FEATURE REQUEST] Argument to disable specific warnings

### ISSUE THREAD

**Issue by silvioprog** [viva64/pvs-studio-cmake-examples#15]
For open source projects, such warnings like `V1042 | This file is marked with copyleft license, which requires you to open the derived source code` doesn't make sense, so it would be nice to provide some argument allowing to disable warnings by comma separated, for example:

`-DSUPPRESS_WARNINGS=V559,V1042`

**Comment by PaulEremeeff** [comment]
Hi,

PVS-Studio does provide a common way (that is, not tied to a particular build system integration) of disabling warnings by special comment\config syntax (the same syntax applies for both pvsconfig's and can be used inside sources). You can read about it [here](https://www.viva64.com/en/m/0017/#IDA6296BF877) in more detail.

In your case, you'l have to add a special comment

`
//-V::1042
`

You can add such a comment to a single source file, or to a common header file (if you want to disable the error globally).

Will this be convenient for your case?

**Comment by silvioprog** [comment]
After adding `//-V::1042` temporally on top of the main include the problem was solved. Thank you! 👍
