### ISSUE TITLE
How to add the project name/version to the PVS-Studio Analysis Results?

### ISSUE THREAD

**Issue by silvioprog** [viva64/pvs-studio-cmake-examples#2]
Hello.

I successfully tested the `pvs-studio-cmake` generating the following result:

![image](https://user-images.githubusercontent.com/1456829/35837400-95df33f8-0ac4-11e8-847f-6bdf050f28c8.png)

but, what do you thing about to allow to identify the project name/version? Something like this:

![image](https://user-images.githubusercontent.com/1456829/35837445-e3c0ff20-0ac4-11e8-9c07-d3c738b89164.png)

I'm not sure if this feature is already available on the `pvs-studio / cmake`.

Thank you!

**Comment by SvyatoslavRazmyslov** [comment]
I think that it is possible to add additional parameters for ```plog-converter``` in the next release.

For example:

```
plog-converter ... --projectName "My awesome C library" --projectVersion "1.2.3" ...
```

**Comment by silvioprog** [comment]
Perfect! I'm going to try that and back with some feedback ...

**Comment by silvioprog** [comment]
Awesome! So the `PVS-Studio.cmake` module could add the following variables:

```cmake
...
# Output options:
# NAME                          project name
# DESCRIPTION                   project description
# VERSION                       project version
# ISSUES                        issues URL
# OUTPUT                        prints report to stdout
# LOG path                      path to report (default: ${CMAKE_CURRENT_BINARY_DIR}/PVS-Studio.log)
# FORMAT format                 format of report
...
```

so:

```cmake
    pvs_studio_add_target(TARGET pvs_studio_analysis ALL
            NAME ${PROJECT_NAME}
            DESCRIPTION ${PROJECT_DESCRIPTION}
            ISSUES ${PROJECT_ISSUES_URL}
            VERSION ${VERSION}
            FORMAT fullhtml
            ANALYZE ${PROJECT_NAME}
            SOURCES ${PROJECT_SOURCE}
            LOG pvs_studio_fullhtml)
```

what do you thing? :smiley:

**Comment by SvyatoslavRazmyslov** [comment]
@silvioprog

> plog-converter ... --projectName "My awesome C library" --projectVersion "1.2.3" ...

Hello, we added this feature in [PVS-Studio Beta](https://www.viva64.com/en/pvs-studio-download-beta/). 

> If you agree I can help improving the PVS-Studio.cmake file adding these new variables.

You can send the Pull Request to improve CMake module, if you want.
